# Generated by Django 3.0.1 on 2019-12-30 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='название камеры')),
                ('slug', models.SlugField(verbose_name='код камеры')),
                ('is_private', models.BooleanField(default=True, verbose_name='приватная')),
                ('my_order', models.PositiveIntegerField(default=0, null=True, verbose_name='сортировка')),
            ],
            options={
                'verbose_name': 'комната',
                'verbose_name_plural': 'комнаты',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='Smile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=18, verbose_name='комбинация символов')),
                ('smile', models.ImageField(upload_to='smile', verbose_name='картинка')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='сортировка')),
            ],
            options={
                'verbose_name': 'смайл',
                'verbose_name_plural': 'смайлы',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='сообщение')),
                ('message_type', models.PositiveSmallIntegerField(choices=[(1, 'стандартное сообщение'), (2, 'пользователь вошёл'), (3, 'пользователь вышел')], default=1, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Room', verbose_name='комната')),
                ('to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='получатель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['-created_at'],
            },
        ),
    ]
