# Generated by Django 3.0.1 on 2019-12-30 20:33

from django.db import migrations, models
import django.db.models.deletion
import meeting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='заголовок')),
                ('date', models.DateField(verbose_name='дата встречи')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'альбомы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, null=True, verbose_name='подпись к фото')),
                ('image', models.ImageField(upload_to=meeting.models.photo_upload, verbose_name='фото')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='сортировка')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='meeting.Album', verbose_name='альбом')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
                'ordering': ['my_order'],
            },
        ),
    ]
